### ISSUE TITLE
HOHOHO Der Weinachtsmann ist da

### ISSUE THREAD

**Issue by Flowercube** [FinnleySeidel/Lightning-Strike#1]
Hohoho, Finnley warst du ein braver Junge?

Ich sehe dich nämlich nicht auf meiner List.
Warst du Artig?

Ja?
Nagut hier ist dein Geschenk.

Sei nächstes Jahr artiger.

Liebe Grüße
Der Osterhase

**Comment by FinnleySeidel** [comment]
Was für ein Geschenk

**Comment by Flowercube** [comment]
Ein Liter Öl. Ein richtiges Vermögen

**Comment by Flowercube** [comment]
Frisch aus Der Usa
